config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id          :bigint           not null, primary key
#  description :text             not null
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Board < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  #バリデーションチェック
  validates :name, presence: true

  validates :description, presence: true
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :bigint           not null, primary key
#  gender       :integer          default("other")
#  introduction :text
#  nickname     :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  enum gender: { male:0, female: 1, other: 2}
  belongs_to :user
  has_one_attached :avatar

  def avatar_image
    if self&.avatar&.attached?
      self.avatar
    else
      'default-avatar.png'
    end
  end
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  deadline   :date
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
class Task < ApplicationRecord
  has_one_attached :eyecatch

  belongs_to :user
  belongs_to :board
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :tasks, dependent: :destroy

  def display_name
    profile&.nickname || self.email.split('@')[0]
  end

  def display_gender
    profile&.gender
  end

  def display_introduction
    profile&.introduction
  end

  def avatar_image
    if self.profile&.avatar&.attached?
      self.profile.avatar
    else
      'default-avatar.png'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def show
    @board = Board.find(params[:id])
  end

  def new
    @board = current_user.boards.build
  end

  def create
    #()にストロングパラメータ
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to board_path(@board), notice: '保存しました'
    else
      flash.now[:error] = '保存できませんでした'
      render :new        #このメソッド内の@boardがnew.html.erbに引き継がれる
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to board_path(@board), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to root_path, notice: '削除しました'
  end

  private

  def board_params
    params.require(:board).permit(:name, :description)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update]

  def show
    @profile = current_user.profile
  end

  def edit
    if current_user.profile.present?
      @profile = current_user.profile
    else
      @profile = current_user.build_profile
    end
  end

  def update
    if current_user.profile.present?
      @profile = current_user.profile
    else
      @profile = current_user.build_profile
    end
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end

  end

  private
  def profile_params
    params.require(:profile).permit(
      :nickname,
      :introduction,
      :gender,
      :avatar
    )
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, only: [:show, :new, :create, :edit, :update, :destroy]

  def show
    @task = Task.find(params[:id])
  end

  def new
    board = Board.find(params[:board_id])
    # Taskクラスのオブジェクトを作成(board_idと共に)
    @task = board.tasks.build
    # Taskのuser_idカラムにcurrent_userを格納
    user = current_user
    @task.user = user
  end

  def create
    board = Board.find(params[:board_id])
    @task = board.tasks.build(task_params)
    user = current_user
    @task.user = user
    if @task.save
      redirect_to board_path(board), notice: '追加しました'
    else
      flash.now[:error] = '追加できませんでした'
      render :new
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def task_params
    params.require(:task).permit(
      :title,
      :content,
      :deadline,
      :eyecatch
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.haml
%h2.page-title Edit Board

%ul
  - @board.errors.full_messages.each do |message|
    %li= message

= form_with(model: @board, local:true) do |f|
  %div
    = f.label :name, "Name"
  %div
    = f.text_field :name, class: 'text'
  %div
    = f.label :description, 'Description'
  %div
    = f.text_area :description
  %div
    = f.submit "Submit", class: 'btn-submit'

app/views/boards/index.html.haml
%h2.page-title All Boards

- @boards.each do |board|
  = link_to board_path(id: board.id) do
    = render partial: 'commons/board', locals: { board: board }
= link_to new_board_path do
  .card_add
    %p + Add new board

app/views/boards/new.html.haml
%h2.page-title New Board

%ul
  - @board.errors.full_messages.each do |message|
    %li= message

= form_with(model: @board, local:true) do |f|
  %div
    = f.label :name, "Name"
  %div
    = f.text_field :name, class: 'text'
  %div
    = f.label :description, 'Description'
  %div
    = f.text_area :description
  %div
    = f.submit "Submit", class: 'btn-submit'

app/views/boards/show.html.haml
.card
  .card_main
    .card_main_content
      .card_main_content_title= @board.name
      .card_main_content_description= @board.description
  .card_detail
    = image_tag @board.user.avatar_image

- @board.tasks.each do |task|
  = link_to board_task_path(id:task.id, board_id:@board.id) do
    .card
      .card_main
        .card_main_content
          .card_main_content_title= task.title
          .card_main_content_description= task.content


= link_to new_board_task_path(@board.id) do
  .card_add
    %p + Add new card

app/views/commons/_board.html.haml
.card
  .card_main
    .card_main_content
      .card_main_content_title= board.name
      .card_main_content_description= board.description
    - if board.user == current_user
      .dropdown
        = image_tag 'actions.svg', class: 'dropbtn'
        .dropdown-content
          = link_to 'Edit', edit_board_path(id: board.id), data: { method: 'get' }
          = link_to 'Delete', board_path(id: board.id), data: { method: 'delete', confirm: '本当に削除していいですか？' }
  .card_detail
    = image_tag board.user.avatar_image

app/views/layouts/application.html.haml
!!!
%html(lang="ja")
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %body
    %header.header
      .header_left
        - if !current_page?(root_path)
          = link_to :back do
            .header_arrow.header_arrow-left
            %br
        - if current_page?(root_path)
          %h1.header_title Boards
        - else
          = link_to root_path do
            %h1.header_title Boards
      .header_right
        - if user_signed_in?
          .dropdown
            = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
            .dropdown-content
              = link_to 'Profile', profile_path, data: { method: 'get' }
              = link_to 'Logout', destroy_user_session_path, data: { method: 'delete' }
        - else
          = link_to 'Login', new_user_session_path, data: { method: 'get'}, class: 'header_loginbtn'
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{class: key}= value
    .container
      = yield

app/views/profiles/edit.html.haml
%ul
  - @profile.errors.full_messages.each do |message|
    %li= message

= form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
  %div
    = f.label :avatar, 'アバター'
  %div
    = f.file_field :avatar
  %div
    = f.label :nickname, 'ハンドルネーム'
  %div
    = f.text_field :nickname, class: 'text'
  %div
    = f.label :introduction, '自己紹介'
  %div
    = f.text_area :introduction
  %div
    = f.label :gender, '性別'
  %div
    = f.select(:gender, Profile.genders.keys, {}, { class: 'text' })
  %div
    = f.submit "Save", class: 'btn-submit'

app/views/profiles/show.html.haml
%h2.page-title Profile
.profile_user
  .profile_user_image
    = image_tag current_user.avatar_image
  .profile_user_basicInfo
    .profile_user_name
      .profile_user_displayName
        #{current_user.display_name} (#{I18n.t("enum.genders.#{current_user.display_gender}")})
      .profile_user_action
        = link_to 'Edit', edit_profile_path
    .profile_user_introduction
      %p= current_user.display_introduction

- current_user.boards.each do |board|
  = link_to board_path(id: board.id) do
    = render partial: 'commons/board', locals: { board: board }

app/views/tasks/new.html.haml
%h2.page-title New Card

%ul
  - @task.errors.full_messages.each do |message|
    %li= message

= form_with(model: @task, url: board_tasks_path(@task.board), method: 'post', local: true) do |f|
  %div
    = f.label :eyecatch, 'Eyecatch'
  %div
    = f.file_field :eyecatch
  %div
    = f.label :title, 'Name'
  %div
    = f.text_field :title, class: 'text'
  %div
    = f.label :content, 'description'
  %div
    = f.text_area :content
  %div
    = f.label :deadline
  %div
    =f.date_field :deadline, class: 'text'
  %div
    = f.submit "Save", class: 'btn-submit'

app/views/tasks/show.html.haml
%h2.page-title= @task.title